/// Resume agent — generates a tailored resume for a qualified job.
///
/// Source of truth: docs/memory/master-resume.md
/// Rule: never add anything not in the master resume.
///
/// Output: outputs/resumes/{company}_{job_id_short}.md
/// After generation the resume is queued for human approval before use.
use crate::approval;
use crate::db::Db;
use crate::models::{Application, Event, Resume};
use anyhow::{bail, Context, Result};
use chrono::Utc;
use std::fs;
use std::path::PathBuf;
use uuid::Uuid;

const MASTER_RESUME_PATH: &str = "docs/memory/master-resume.md";
const OUTPUT_DIR: &str = "outputs/resumes";

pub fn run(db: &Db, job_id: &str) -> Result<PathBuf> {
    let job = db.get_job(job_id)
        .with_context(|| format!("Job '{}' not found", job_id))?;

    if job.qualified != Some(true) {
        bail!("Job '{}' is not qualified. Run `career-os qualify` first.", job_id);
    }

    let master = fs::read_to_string(MASTER_RESUME_PATH)
        .with_context(|| format!("Cannot read master resume at {}", MASTER_RESUME_PATH))?;

    let version = db.next_resume_version(job_id)?;
    let content = generate_tailored(&job, &master);

    fs::create_dir_all(OUTPUT_DIR)?;
    let slug = slug(&job.company);
    let short_id = &job.id[..8];
    let filename = format!("{}_{}_v{}.md", slug, short_id, version);
    let path = PathBuf::from(OUTPUT_DIR).join(&filename);

    fs::write(&path, &content)
        .with_context(|| format!("Cannot write resume to {}", path.display()))?;

    // Record in DB
    let resume = Resume {
        id: Uuid::new_v4().to_string(),
        job_id: job_id.to_string(),
        version,
        content: content.clone(),
        format: "txt".to_string(),
        generated_at: Utc::now(),
        approved: false,
        approved_at: None,
        artifact_path: path.to_string_lossy().to_string(),
    };
    db.insert_resume(&resume)?;

    // Create a draft application
    let app = Application::new(job_id);
    let app = Application { resume_id: Some(resume.id.clone()), ..app };
    db.insert_application(&app)?;

    // Queue for approval
    approval::enqueue(
        db,
        "resume",
        &resume.id,
        &format!("Resume v{} for {} @ {}", version, job.title, job.company),
        &path.to_string_lossy(),
    )?;

    // Emit event
    db.emit_event(&Event::new(
        "ResumeGenerated",
        serde_json::json!({
            "resume_id": resume.id,
            "job_id": job_id,
            "application_id": app.id,
            "version": version,
        }),
        "resume",
    ))?;

    Ok(path)
}

fn generate_tailored(job: &crate::models::Job, master: &str) -> String {
    let keywords = find_keyword_overlaps(job, master);
    let keyword_list = if keywords.is_empty() {
        "— none found; review master resume for relevant keywords".to_string()
    } else {
        keywords.join(", ")
    };

    format!(
        "<!-- TAILORED RESUME — Generated by CareerOS -->
<!-- Target: {} @ {} -->
<!-- Job URL: {} -->
<!-- Score: {} | Generated: {} -->
<!-- ACTION REQUIRED: Review and edit before submitting. -->
<!-- Never add experience not in the master resume.     -->

# Resume — Tailored for {} @ {}

---

## Tailoring Analysis

**Keywords found in both job description and master resume:**
{}

**Recommended actions before submitting:**
- Move the most relevant bullet points to the top of each role
- Mirror exact terminology from the job description where your experience matches
- Ensure the Professional Summary opens with language matching the job title
- Verify the Core Competencies section lists the keywords above (if verified)

---

{}
",
        job.title,
        job.company,
        job.url,
        job.score.map(|s| s.to_string()).unwrap_or_else(|| "?".to_string()),
        chrono::Utc::now().format("%Y-%m-%d"),
        job.title,
        job.company,
        keyword_list,
        master.trim(),
    )
}

/// Find keywords from the job description that also appear in the master resume.
fn find_keyword_overlaps(job: &crate::models::Job, master: &str) -> Vec<String> {
    const KEYWORDS: &[&str] = &[
        "technical program manager", "tpm", "program manager", "program management",
        "cross-functional", "stakeholder", "roadmap", "agile", "scrum",
        "ai", "ml", "llm", "machine learning", "artificial intelligence",
        "process improvement", "six sigma", "lean", "okr", "kpi",
        "data-driven", "metrics", "sql", "python",
        "risk mitigation", "executive communication", "budget",
        "vendor", "compliance", "security", "infrastructure",
    ];

    let desc_lower = job.description.to_lowercase();
    let master_lower = master.to_lowercase();

    KEYWORDS
        .iter()
        .filter(|kw| desc_lower.contains(*kw) && master_lower.contains(*kw))
        .map(|kw| kw.to_string())
        .collect()
}

fn slug(s: &str) -> String {
    s.to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '-' })
        .collect::<String>()
        .split('-')
        .filter(|p| !p.is_empty())
        .collect::<Vec<_>>()
        .join("-")
}
